# -----------------------------------------------------------------------------
# Goshawk Occupancy Analysis â€“ Run Configuration
#
# This file defines high-level configuration parameters used to control
# data extraction and analysis workflows, including which Natural Resource
# District(s) to process, output locations, and other run-specific settings.
#
# Values in this file are intended to be modified between runs without
# changing analysis code.
# -----------------------------------------------------------------------------

[district]
code = "DPG"

[nesting_vri_params]
proj_age_1 = 100    # query includes values higher than this value 
proj_height = 19.5  # query includes values higher than this value
crown_closure = 26  # query includes values higher than this value
site_index = 10     # Used in queries as ceiling / less than value

[foraging_vri_params]
proj_age_1 = 40    # query includes values higher than this value 
min_disturbance_year = 1986 # query includes values higher than this value 

[tsa]
feature_id = 365     # 333 is the code for Robson Valley TSA in its entirety

[geoprocessing]
tol = 0.005

[raster]
out_crs = "EPSG:3005" #BC Albers
pixel_size = 30.0
all_touched = false
nodata = 255
dtype = "uint8"
compress = "DEFLATE"
tiled = true
blockxsize = 256
blockysize = 256
predictor = 2
geojson_crs_if_missing = "EPSG:4326"
pad_pixels = 0
age_field = "PROJ_AGE_1"
